(function (root) {
  'use strict';

  root.YNABCategoryRules = {
  "exact": {
    "Supermercado la punt san antonio": "Casa: 🛒 Supermercado",
    "Segur. falabella rr. santiago": "Casa: 🧾 Cuentas",
    "Mercadopago amasa las condes": "Casa: 🛒 Supermercado",
    "Neat cuentas basicas san felipe": "Casa: 🧾 Cuentas",
    "Restaurant casa orie santiago": "Otros: 🍿 Esparcimiento",
    "Payu diario financi santiago": "Casa: 🎞️ Suscripciones",
    "Tienda mall plaza los santiago": "Casa: 🚗 Transporte",
    "Colegio instituto tere tasa int. 0,00%": "Educación: 🎒 Colegios",
    "Payu uber trip santiago": "Casa: 🚗 Transporte",
    "10176 bk la reina santiago": "Otros: 🍿 Esparcimiento",
    "40533 sbx rosario nort": "Otros: 🍽️ Almuerzo Trabajo",
    "40632 sbx portal la re": "Otros: 🍿 Esparcimiento",
    "administradora ventas": "Casa: 🚗 Transporte",
    "almacen eve": "Casa: 🛒 Supermercado",
    "antartica plaza egana santiago": "Educación: 🎒 Colegios",
    "antartica portal la re": "Otros: 🎁 Gifts",
    "antigua fuente": "Otros: 🍽️ Almuerzo Trabajo",
    "apple com compras": "Otros: 🛍️ Otras Compras",
    "aramco compras": "Otros: 🍽️ Almuerzo Trabajo",
    "balcao": "Otros: 🍽️ Almuerzo Trabajo",
    "bamers": "Casa: 👖 Cuidado Personal",
    "barbizon santiago": "Casa: 👖 Cuidado Personal",
    "bariloche casablanca": "Otros: 🍿 Esparcimiento",
    "bbw plaza egana": "Otros: 🎁 Gifts",
    "belen gallardo psicologa": "Salud: 🧑‍⚕️ Médicos",
    "bernardo de jesus pave": "Casa: 🛒 Supermercado",
    "bis plaza egana": "Otros: 😓 Shame, no recuerdo",
    "blupoint web": "Otros: 🛍️ Otras Compras",
    "buscalibre com santiago": "Otros: 🎁 Gifts",
    "c verde ossandon 1188 santiago": "Salud: 💊 Farmacia",
    "cafe delicia": "Otros: 🍿 Esparcimiento",
    "cafeteria": "Otros: 🍽️ Almuerzo Trabajo",
    "canelillo": "Casa: 🛒 Supermercado",
    "car wash 7 la reina": "Casa: 🚗 Transporte",
    "casa ideas algarrobo": "Otros: 🛍️ Otras Compras",
    "castano": "Otros: 🍽️ Almuerzo Trabajo",
    "central parking system": "Casa: 🚗 Transporte",
    "choco churros": "Otros: 🍿 Esparcimiento",
    "cine hoyts plaza p hur santiago": "Otros: 🍿 Esparcimiento",
    "cinepolis eb chile": "Otros: 🍿 Esparcimiento",
    "clin uandes santiago": "Salud: 🧑‍⚕️ Médicos",
    "clinica univ de los an": "Salud: 🧑‍⚕️ Médicos",
    "clinica universidad de los andes": "Salud: 🧑‍⚕️ Médicos",
    "coaniquem store": "Otros: 🛍️ Otras Compras",
    "coaniquem store la re": "Otros: 🛍️ Otras Compras",
    "colegio instituto t san cf 01 10": "Educación: 🎒 Colegios",
    "colegio la fontaine san cc 02 10": "Educación: 🎒 Colegios",
    "comercial baiyi": "Otros: 🍿 Esparcimiento",
    "comercial casa china s santiago": "Casa: 🛒 Supermercado",
    "comercial clover las c": "Casa: 🛒 Supermercado",
    "comercial ely spa san anto": "Otros: 🛍️ Otras Compras",
    "comercial panificadora": "Casa: 🛒 Supermercado",
    "comision administracion mensual": "Casa: 🧾 Cuentas",
    "compara seg auto compras": "Casa: 🚗 Transporte",
    "compara seguro auto ca compras": "Casa: 🚗 Transporte",
    "copec": "Casa: 🚗 Transporte",
    "copec 40039": "Casa: 🚗 Transporte",
    "copec app compras": "Casa: 🛒 Supermercado",
    "copec zervo": "Casa: 🚗 Transporte",
    "copec zervo las condes": "Casa: 🚗 Transporte",
    "cps copec poe": "Casa: 🛒 Supermercado",
    "crunchyroll": "Casa: 🎞️ Suscripciones",
    "crunchyroll crunchyrol compras": "Casa: 🎞️ Suscripciones",
    "cruz verde": "Salud: 💊 Farmacia",
    "cruz verde l9122 algarrob": "Salud: 💊 Farmacia",
    "cv 1244": "Salud: 💊 Farmacia",
    "dcto bencineras wallet": "Casa: 🚗 Transporte",
    "decathlon": "Casa: 👖 Cuidado Personal",
    "decathlon portal la reina": "Otros: 🎁 Gifts",
    "dentista": "Salud: 🧑‍⚕️ Médicos",
    "dimeiggs compras": "Educación: 🎒 Colegios",
    "dlocal facebook": "Otros: 🛍️ Otras Compras",
    "doremi la reina santiago": "Casa: 🛒 Supermercado",
    "dp falabella com santiago": "Casa: 👖 Cuidado Personal",
    "easy las condes compras": "Otros: 🎁 Gifts",
    "eco farmacias": "Salud: 💊 Farmacia",
    "el rosal": "Otros: 🍽️ Almuerzo Trabajo",
    "empanadissima compras": "Otros: 🍿 Esparcimiento",
    "emporio la rosa": "Otros: 🍿 Esparcimiento",
    "encuadrado compras": "Salud: 🧑‍⚕️ Médicos",
    "estetica pq ltda santiago": "Casa: 👖 Cuidado Personal",
    "eve": "Casa: 🛒 Supermercado",
    "eve santiago": "Casa: 🛒 Supermercado",
    "express algarrobo algarrobo": "Casa: 🛒 Supermercado",
    "fabiola vannus": "Casa: 🛒 Supermercado",
    "falabella": "Casa: 👖 Cuidado Personal",
    "falabella los dominico santiago": "Otros: 🎁 Gifts",
    "farmacia comunitaria": "Salud: 💊 Farmacia",
    "farmacia litoral": "Salud: 💊 Farmacia",
    "farmacias salcobrand": "Salud: 💊 Farmacia",
    "feria": "Casa: 🛒 Supermercado",
    "ferreteria": "Otros: 🎁 Gifts",
    "flannerys beer house": "Otros: 🍿 Esparcimiento",
    "flores": "Casa: 👖 Cuidado Personal",
    "flow asefy": "Casa: 👵 Nana",
    "francalimpieza": "Otros: 🛍️ Otras Compras",
    "galileo libros": "Educación: 🎒 Colegios",
    "grupo bismarck spa": "Casa: 🛒 Supermercado",
    "h m": "Casa: 👖 Cuidado Personal",
    "hc mall plaza egana": "Otros: 🎁 Gifts",
    "heladeria juanito": "Otros: 🍿 Esparcimiento",
    "help seguros pat": "Casa: 🧾 Cuentas",
    "hernan": "Casa: 🛒 Supermercado",
    "hip lider los dominico": "Educación: 🎒 Colegios",
    "hip lider ppe de gales santiago": "Casa: 🛒 Supermercado",
    "ikea": "Casa: 🏠 Vivienda",
    "imp y exp cosmos": "Casa: 🛒 Supermercado",
    "imp y exp cosmos mar santiago": "Casa: 🛒 Supermercado",
    "imp y exp cosmos marke": "Casa: 🛒 Supermercado",
    "importadora mares del": "Otros: 🛍️ Otras Compras",
    "impuestos deb impto": "Casa: 🧾 Cuentas",
    "ino autoservicio santiago": "Casa: 🚗 Transporte",
    "ino santiago": "Salud: 🧑‍⚕️ Médicos",
    "integramedica": "Salud: 🧑‍⚕️ Médicos",
    "inversiones duandy": "Otros: 🎁 Gifts",
    "inversiones y servicos": "Otros: 🍿 Esparcimiento",
    "iopa": "Salud: 🧑‍⚕️ Médicos",
    "johnny rockets egana": "Otros: 🍿 Esparcimiento",
    "juan retamal santiago": "Casa: 🛒 Supermercado",
    "jugueria peruana mut": "Otros: 🍿 Esparcimiento",
    "jumbo": "Casa: 🛒 Supermercado",
    "jumbo oneclick compras": "Casa: 🛒 Supermercado",
    "jumbo oneclick cred compras": "Casa: 🛒 Supermercado",
    "jumbo oneclick santiago": "Casa: 🛒 Supermercado",
    "justo providencia": "Otros: 🍽️ Almuerzo Trabajo",
    "k099": "Otros: 🍿 Esparcimiento",
    "k099 la reina": "Otros: 🍿 Esparcimiento",
    "kclub supermarket spa": "Casa: 🛒 Supermercado",
    "kios club": "Casa: 🛒 Supermercado",
    "kiosko playa": "Casa: 🛒 Supermercado",
    "kioskos kfc": "Otros: 🍿 Esparcimiento",
    "la costeria": "Otros: 🍿 Esparcimiento",
    "la nonna": "Casa: 🛒 Supermercado",
    "la reina santiago": "Casa: 🛒 Supermercado",
    "la virgen presidente r": "Otros: 🍿 Esparcimiento",
    "laboratorio uc": "Salud: 🧑‍⚕️ Médicos",
    "laik wtc las condes": "Otros: 🍽️ Almuerzo Trabajo",
    "lapiz lopez": "Educación: 🎒 Colegios",
    "las bezanilla": "Casa: 🛒 Supermercado",
    "latam com xp otras compras": "Otros: 🍿 Esparcimiento",
    "led studio": "Casa: 🏠 Vivienda",
    "lenovo": "Otros: 🛍️ Otras Compras",
    "libreria antartica mut": "Otros: 🍿 Esparcimiento",
    "libreria nacional plaz compras": "Casa: 🛒 Supermercado",
    "lider cl": "Casa: 🛒 Supermercado",
    "lider cl tienda ebpay santiago": "Casa: 🛒 Supermercado",
    "liga ch contra la e la": "Salud: 💊 Farmacia",
    "liga chilena contra la epilepsia": "Salud: 💊 Farmacia",
    "limonada": "Otros: 🎁 Gifts",
    "little caesar jose a santiago": "Otros: 🍿 Esparcimiento",
    "los pozos spa": "Otros: 🍽️ Almuerzo Trabajo",
    "macerado": "Otros: 🍿 Esparcimiento",
    "make up": "Otros: 🛍️ Otras Compras",
    "mall chino": "Otros: 🛍️ Otras Compras",
    "mamut mall plaza egana": "Otros: 🍿 Esparcimiento",
    "mayan": "Otros: 🍿 Esparcimiento",
    "mc donalds": "Otros: 🍿 Esparcimiento",
    "mc donalds santiago": "Otros: 🍿 Esparcimiento",
    "meki compras": "Salud: 💊 Farmacia",
    "mercado circular": "Casa: 🛒 Supermercado",
    "mercado pago 5": "Casa: 🚗 Transporte",
    "mercado pago 5 tcom compras": "Casa: 🚗 Transporte",
    "mercado pago 5 tcom santiago": "Casa: 🚗 Transporte",
    "mercado pago almacen": "Casa: 🛒 Supermercado",
    "mercadopago almacen compras": "Casa: 🛒 Supermercado",
    "mercadopago amasa": "Casa: 🛒 Supermercado",
    "mercadopago bipqr compras": "Casa: 🚗 Transporte",
    "mercadopago bipqr las condes": "Casa: 👖 Cuidado Personal",
    "mercadopago caleu": "Otros: 🍿 Esparcimiento",
    "mercadopago cantabri": "Otros: 🍿 Esparcimiento",
    "mercadopago comercia": "Otros: 🍿 Esparcimiento",
    "mercadopago dunkin": "Otros: 🍽️ Almuerzo Trabajo",
    "mercadopago eliana": "Casa: 🛒 Supermercado",
    "mercadopago envoltor las condes": "Otros: 🍿 Esparcimiento",
    "mercadopago ermakspa": "Casa: 🚗 Transporte",
    "mercadopago ermakspa las condes": "Otros: 🍽️ Almuerzo Trabajo",
    "mercadopago eve compras": "Casa: 🛒 Supermercado",
    "mercadopago grupo axo": "Otros: 🎁 Gifts",
    "mercadopago invlinkn": "Educación: 🎒 Colegios",
    "mercadopago julioenr": "Casa: 🛒 Supermercado",
    "mercadopago kcincosp": "Otros: 🍽️ Almuerzo Trabajo",
    "mercadopago kioscoca las cond": "Otros: 🍿 Esparcimiento",
    "mercadopago lasergam": "Otros: 🍿 Esparcimiento",
    "mercadopago littleca": "Otros: 🍿 Esparcimiento",
    "mercadopago luna": "Otros: 🛍️ Otras Compras",
    "mercadopago mercadol": "Casa: 👖 Cuidado Personal",
    "mercadopago mercadol las condes": "Otros: 🍿 Esparcimiento",
    "mercadopago panleonm": "Casa: 🛒 Supermercado",
    "mercadopago pizzlare las cond": "Otros: 🍿 Esparcimiento",
    "mercadopago pluspark": "Casa: 🚗 Transporte",
    "mercadopago pocaspec": "Casa: 🛒 Supermercado",
    "mercadopago pueblovi": "Otros: 🍿 Esparcimiento",
    "mercadopago sodexoch": "Otros: 🍿 Esparcimiento",
    "mercadopago storecof": "Casa: 🛒 Supermercado",
    "mercadopago sushiira": "Otros: 🍿 Esparcimiento",
    "mercadopago vigahome las cond": "Casa: 🏠 Vivienda",
    "merpagoalimentoschia la reina": "Casa: 🛒 Supermercado",
    "merpagofarmexspa las condes": "Salud: 💊 Farmacia",
    "merpagofernandodoro la reina": "Casa: 🛒 Supermercado",
    "merpagogrupoaxo huechuraba": "Otros: 🎁 Gifts",
    "merpagoventaalpormeno puente alto": "Otros: 🍿 Esparcimiento",
    "mil maravillas": "Casa: 🛒 Supermercado",
    "mirax costanera santiago": "Otros: 🍿 Esparcimiento",
    "mp clinicauniversida las cond": "Salud: 🧑‍⚕️ Médicos",
    "mp decathlonchilespa compras": "Otros: 🎁 Gifts",
    "mp decathlonchilespa las condes": "Otros: 🎁 Gifts",
    "mp max las cond": "Casa: 🎞️ Suscripciones",
    "mp micocacola cred compras": "Casa: 🛒 Supermercado",
    "mp micocacola las cond": "Casa: 🛒 Supermercado",
    "mp micocacola las condes": "Casa: 🛒 Supermercado",
    "mp ondemand las condes": "Otros: 🛍️ Otras Compras",
    "mp opticasluxott": "Salud: 💊 Farmacia",
    "mp soapbomberos": "Casa: 🚗 Transporte",
    "mp socklabspa las condes": "Otros: 🎁 Gifts",
    "municipalidad la reina": "Casa: 🚗 Transporte",
    "museo paleontologico": "Otros: 🍿 Esparcimiento",
    "mylutecno algarrobo": "Otros: 🍿 Esparcimiento",
    "neat cuentas basicas": "Casa: 🧾 Cuentas",
    "neat cuentas basicas san feli": "Casa: 🧾 Cuentas",
    "nh collection plaza": "Otros: 🍽️ Almuerzo Trabajo",
    "nintendo of america": "Otros: 🍿 Esparcimiento",
    "niu express plaza e": "Otros: 🍿 Esparcimiento",
    "nueva soc gastronom santiago": "Otros: 🍿 Esparcimiento",
    "orld trade center santiago": "Otros: 🍽️ Almuerzo Trabajo",
    "oxxo": "Casa: 🛒 Supermercado",
    "panaderia": "Casa: 🛒 Supermercado",
    "panaderia los maitenes": "Casa: 🛒 Supermercado",
    "panaderia los maitenes santiago": "Casa: 🛒 Supermercado",
    "paradiso cafe": "Otros: 🍽️ Almuerzo Trabajo",
    "parque intercomunal": "Otros: 🍿 Esparcimiento",
    "parque tricao": "Otros: 🍿 Esparcimiento",
    "pasajebus compras": "Casa: 🚗 Transporte",
    "pat vida security": "Casa: 🧾 Cuentas",
    "pat vida security santiago": "Casa: 🧾 Cuentas",
    "paycwps british royal compras": "Educación: 🎒 Colegios",
    "payscan snack center compras": "Casa: 🛒 Supermercado",
    "payu diario financiero": "Casa: 🎞️ Suscripciones",
    "payu uber eats compras": "Otros: 🍿 Esparcimiento",
    "payu uber eats santiago": "Otros: 🍿 Esparcimiento",
    "payu uber trip compras": "Casa: 🚗 Transporte",
    "plaza egana": "Otros: 🎁 Gifts",
    "podovita spa": "Casa: 👖 Cuidado Personal",
    "pronto copec": "Otros: 🍽️ Almuerzo Trabajo",
    "pronto costanera e 6 2": "Otros: 🍿 Esparcimiento",
    "pronto p de gales 251 santiago": "Casa: 🛒 Supermercado",
    "pronto san antonio": "Otros: 🍿 Esparcimiento",
    "puc web pregrado": "Educación: 🏅 Educación Continua",
    "red movilidad santiago": "Casa: 🚗 Transporte",
    "redgloba la clave del": "Otros: 🍿 Esparcimiento",
    "redgloba local 99752 1": "Casa: 🛒 Supermercado",
    "restaurant casa oriental": "Otros: 🍿 Esparcimiento",
    "ripley": "Casa: 👖 Cuidado Personal",
    "ripley costanera cente santiago": "Casa: 👖 Cuidado Personal",
    "ripley credito r santiago": "Casa: 👖 Cuidado Personal",
    "ripley los dominicos cred compras": "Casa: 👖 Cuidado Personal",
    "ripley plaza egana santiago": "Casa: 👖 Cuidado Personal",
    "rosario norte 2": "Otros: 🍿 Esparcimiento",
    "saba plaza mekis": "Casa: 🚗 Transporte",
    "saba plaza mekis santiago": "Casa: 🚗 Transporte",
    "salcobrand carloss oss": "Salud: 💊 Farmacia",
    "salcobrand los andes 5": "Salud: 💊 Farmacia",
    "salud mental": "Salud: 🧑‍⚕️ Médicos",
    "santa isabel laura rod santiago": "Casa: 🛒 Supermercado",
    "santa teresita": "Casa: 🛒 Supermercado",
    "sb 884 compras": "Salud: 💊 Farmacia",
    "sbarro": "Otros: 🍿 Esparcimiento",
    "segur falabella rr compras": "Inversiones y Ahorro: 🏢 Departamento",
    "servicios y comercial las condes": "Otros: 🍽️ Almuerzo Trabajo",
    "skechers plaza egana": "Casa: 👖 Cuidado Personal",
    "sodimac la reina": "Casa: 🏠 Vivienda",
    "spid las brujas": "Casa: 🛒 Supermercado",
    "starbucks coffee las co": "Otros: 🍿 Esparcimiento",
    "strip larrain compras": "Casa: 🛒 Supermercado",
    "strip larrain santiago": "Casa: 🛒 Supermercado",
    "suc providencia": "Salud: 💊 Farmacia",
    "suc restaurante buteco": "Otros: 💰 Reembolsables",
    "sumup santa rita": "Otros: 🎁 Gifts",
    "supermercado la puntilla": "Casa: 🛒 Supermercado",
    "sushi delivery": "Otros: 🍿 Esparcimiento",
    "territoria apoquindo": "Casa: 🚗 Transporte",
    "the body shop": "Otros: 🎁 Gifts",
    "tienda mall plaza egan": "Casa: 🚗 Transporte",
    "tienda mall plaza egan compras": "Casa: 🚗 Transporte",
    "tienda mall plaza egan santiago": "Casa: 🚗 Transporte",
    "tienda paper mark": "Otros: 🎁 Gifts",
    "tiendas sm": "Educación: 🎒 Colegios",
    "tobalaba santiago": "Otros: 🍽️ Almuerzo Trabajo",
    "toma de muestra 2": "Salud: 🧑‍⚕️ Médicos",
    "trebo santiago": "Educación: 🎒 Colegios",
    "turismo marianela mora": "Otros: 🍿 Esparcimiento",
    "tuu ajedrez coffee": "Otros: 🍽️ Almuerzo Trabajo",
    "tuu choco churros spa": "Otros: 🍿 Esparcimiento",
    "tuu chocochurrosspa": "Otros: 🍿 Esparcimiento",
    "tuu estacionamientos s": "Casa: 🚗 Transporte",
    "tuu estacionamientos s algarrob": "Casa: 🚗 Transporte",
    "u andes cta paciente": "Salud: 🧑‍⚕️ Médicos",
    "uber": "Casa: 🚗 Transporte",
    "uber compras": "Casa: 🎞️ Suscripciones",
    "uber las condes": "Casa: 🚗 Transporte",
    "unimarc": "Casa: 🛒 Supermercado",
    "unimarc ppe de gales": "Casa: 🛒 Supermercado",
    "unimarc ppe de gales santiago": "Casa: 🛒 Supermercado",
    "vendomatica 114": "Casa: 🛒 Supermercado",
    "wendy s": "Otros: 🍿 Esparcimiento",
    "western union": "Otros: 🎁 Gifts",
    "zapateria": "Otros: 🛍️ Otras Compras",
    "zara": "Casa: 👖 Cuidado Personal"
  },
  "generated_at_utc": "2026-02-28T02:01:39+00:00",
  "patterns": [
    {
      "category": "Casa: 🛒 Supermercado",
      "type": "startsWith",
      "value": "jumbo"
    },
    {
      "category": "Casa: 🛒 Supermercado",
      "type": "startsWith",
      "value": "panaderia"
    },
    {
      "category": "Casa: 👖 Cuidado Personal",
      "type": "startsWith",
      "value": "ripley"
    },
    {
      "category": "Casa: 🛒 Supermercado",
      "type": "startsWith",
      "value": "unimarc"
    },
    {
      "category": "Casa: 🚗 Transporte",
      "type": "contains",
      "value": "parking"
    }, 
    {
      "category": "Casa: 🏠 Vivienda",
      "type": "contains",
      "value": "vigahome"
    }, 
    {
      "category": "Salud: 💊 Farmacia",
      "type": "contains",
      "value": "salcobrand"
    }, 
    {
      "category": "Otros: 🍿 Esparcimiento",
      "type": "contains",
      "value": "Johnny rockets"
    },
    {
      "category": "Salud: 🧑‍⚕️ Médicos",
      "type": "startsWith",
      "value": "Odontologia"
    },
    {
      "category": "Casa: 👖 Cuidado Personal",
      "type": "startsWith",
      "value": "Bamers"
    },
    {
      "category": "Casa: 🛒 Supermercado",
      "type": "contains",
      "value": "Amasanderia"
    },
    {
      "category": "Salud: 🧑‍⚕️ Médicos",
      "type": "contains",
      "value": "Clinica"
    },
    {
      "category": "Salud: 💊 Farmacia",
      "type": "contains",
      "value": "Meki"
    },
    {
      "value": "Cruz verde",
      "type": "contains",
      "category": "Salud: 💊 Farmacia"
    },
    {
      "value": "clover",
      "type": "contains",
      "category": "Casa: 🛒 Supermercado"
    },
    {
      "value": "nintendo",
      "type": "contains",
      "category": "Otros: 🍿 Esparcimiento"
    },
    {
      "value": "La Nonna",
      "type": "startsWith",
      "category": "Casa: 🛒 Supermercado"
    },
    {
      "value": "crunchyroll",
      "type": "startsWith",
      "category": "Casa: 🎞️ Suscripciones"
    },
    {
      "value": "Liga ch contra",
      "type": "startsWith",
      "category": "Salud: 💊 Farmacia"
    },
    {
      "value": "U. andes",
      "type": "startsWith",
      "category": "Salud: 🧑‍⚕️ Médicos"
    }
  ],
  "skip": [
    "transfer itau",
    "starting balance",
    "abono canje compra tc",
    "cashback com"
  ],
  "source_file": "YNAB Export Full Itau Nacional History.tsv"
};
})(typeof window !== 'undefined' ? window : this);
